# Generated by Django 2.0.7 on 2018-07-31 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20180731_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('not-specified', 'Not-specified'), ('female', 'Female'), ('male', 'Male')], max_length=80, null=True),
        ),
    ]
