# Generated by Django 2.0.7 on 2018-07-31 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20180731_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('not-specified', 'Not-specified'), ('male', 'Male'), ('female', 'Female')], max_length=80, null=True),
        ),
    ]
