# Generated by Django 2.0.7 on 2018-07-31 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_auto_20180801_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('not-specified', 'Not-specified'), ('female', 'Female'), ('male', 'Male')], max_length=80, null=True),
        ),
    ]
